### ISSUE TITLE
[BUG] server crashes instantly after startup.

### ISSUE THREAD

**Issue by LazyGamer1111** [PigCart/UPeeNPiss#4]
If i start up the server it instantly crashes with an error.

**Comment by PigCart** [comment]
leave crashlogs when reporting crashes otherwise your reports are useless.
I assume you're trying to use an older version of the mod or minecraft. I've backported the latest version so if that is the case try the 1.18.x and below version https://modrinth.com/mod/dedicatedmcupnp/versions

**Comment by LazyGamer1111** [comment]
> leave crashlogs when reporting crashes otherwise your reports are useless. I assume you're trying to use an older version of the mod or minecraft. I've backported the latest version so if that is the case try the 1.18.x and below version https://modrinth.com/mod/dedicatedmcupnp/versions

i forgot i left this report, it starts up normally and then, i get this error:

[18:40:22] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dedicatedmcupnp'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:353) ~[com_fasterxml_jackson_dataformatyaml-2.13.0-64745faae2d50d23.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.13.0-64745faae2d50d23.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[com_fasterxml_jackson_core_jacksbind-2.12.4-82a99bb0904951ea.jar:?]
        at pigcart.dedicatedmcupnp.DedicatedMcUpnp.onInitialize(DedicatedMcUpnp.java:67) ~[dedicatedmcupnp-1.2.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 7 more

**Comment by PigCart** [comment]
I'll need the actual full crash report to figure out what's happening, not just part of the error message. You can find them in the crash-reports folder.
seems like maybe a dependency is missing or not loading somehow. not sure why. try redownloading and double check you're using the right version.

**Comment by LazyGamer1111** [comment]
[21:02:07] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[21:02:07] [ForkJoinPool-1-worker-4/WARN]: Mod io_netty_netty-codec-haproxy uses the version 4.1.78.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:02:07] [ForkJoinPool-1-worker-2/WARN]: Mod net_dv8tion_jda uses the version 4.4.0_352 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0_352'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:02:07] [main/INFO]: Loading 138 mods:
	- antishulkerdupe 1.0.0
	- antixray 1.2.4
	- aqupdhat 1.19-2.3.2
	- autoconfig1u 3.4.0 via image2map
	- autowhitelist 1.1.2
	- banhammer 0.5.2+1.19
	- c2me 0.2.0+alpha.8.2
	- c2me-base 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-general-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.8.2 via c2me
	- c2me-notickvd 0.2.0+alpha.8.2 via c2me
	- c2me-opts-allocs 0.2.0+alpha.8.2 via c2me
	- c2me-opts-chunk-access 0.2.0+alpha.8.2 via c2me
	- c2me-opts-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-opts-math 0.2.0+alpha.8.2 via c2me
	- c2me-opts-scheduling 0.2.0+alpha.8.2 via c2me
	- c2me-opts-worldgen-general 0.2.0+alpha.8.2 via c2me
	- c2me-opts-worldgen-vanilla 0.2.0+alpha.8.2 via c2me
	- c2me-rewrites-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-server-utils 0.2.0+alpha.8.2 via c2me
	- c2me-threading-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-threading-lighting 0.2.0+alpha.8.2 via c2me
	- c2me-threading-scheduling 0.2.0+alpha.8.2 via c2me
	- c2me-threading-worldgen 0.2.0+alpha.8.2 via c2me
	- carpet 1.4.79
	- carpet-extra 1.4.83
	- clean-logs 1.1.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.0.75
	- club_minnced_discord-webhooks 0.8.0 via banhammer
	- com_electronwill_night-config_core 3.6.5 via c2me
	- com_electronwill_night-config_toml 3.6.5 via c2me
	- com_fasterxml_jackson_core_jackson-annotations 2.12.4 via dedicatedmcupnp
	- com_fasterxml_jackson_core_jackson-core 2.12.4 via dedicatedmcupnp
	- com_fasterxml_jackson_core_jackson-databind 2.12.4 via dedicatedmcupnp
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_ibm_async_asyncutil 0.1.0 via c2me
	- com_moandjiezana_toml_toml4j 0.7.2 via antixray
	- com_neovisionaries_nv-websocket-client 2.14 via autowhitelist
	- com_squareup_okhttp3_okhttp 3.14.9 via banhammer
	- com_squareup_okio_okio 1.17.2 via autowhitelist
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig-base 2.0.0 via homabric
	- dedicatedmcupnp 1.2.1
	- ec-core 1.2.1-mc1.19 via essential_commands
	- essential_commands 0.28.1-mc1.19
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via autowhitelist
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.8.0+kotlin.1.7.0 via homabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via autowhitelist
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.2-SNAPSHOT via essential_commands
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.9
	- ferritecore 4.2.1
	- golfiv 0.6.0
	- homabric 2.0.1+1.19
	- image2map 0.2.3
	- invview 1.4.9-1.19+
	- io_netty_netty-codec-haproxy 4.1.78.Final via proxy_protocol_support
	- java 17
	- krypton 0.2.0
	- lazydfu 0.1.3
	- lithium 0.8.1
	- luckperms 5.4.36
	- minecarttweaks 1.6
	- minecraft 1.19
	- mysql_mysql-connector-java 8.0.29 via banhammer
	- net_dv8tion_jda 4.4.0_352 via autowhitelist
	- net_sf_trove4j_trove4j 3.0.3 via autowhitelist
	- onedatastore 0.1.2+1.19 via pingspam
	- org_apache_commons_commons-collections4 4.1 via autowhitelist
	- org_jetbrains_annotations 22.0.0 via banhammer
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.17.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_json_json 20210307 via banhammer
	- org_slf4j_slf4j-api 1.7.32 via banhammer
	- org_threadly_threadly 7.0 via c2me
	- org_xerial_sqlite-jdbc 3.36.0.3 via banhammer
	- org_yaml_snakeyaml 1.30 via viafabric
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- phosphor 0.8.1
	- pingspam 1.3.1+1.19
	- placeholder-api 2.0.0-beta.7+1.19 via essential_commands
	- player-data-api 0.1.0+1.18 via styledplayerlist
	- playerabilitylib 1.6.0 via essential_commands
	- proxy_protocol_support 1.0.2-fabric
	- recipecache 0.2.0-1.19
	- server_translations_api 1.4.14+1.19-rc2 via aqupdhat
	- sgui 1.1.0+1.19 via banhammer
	- styledchat 1.3.3+1.19
	- styledplayerlist 2.2.1+1.19
	- vanish 1.4.1
	- viafabric 0.4.8+12-main
	- viafabric-mc119 0.4.8+12-main via viafabric
	- viaversion 4.4.0 via viafabric
[21:02:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/bjorn/enderstorm-2/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[21:02:08] [main/INFO]: Compatibility level set to JAVA_16
[21:02:08] [main/INFO]: Compatibility level set to JAVA_17
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.threading.scheduling.mixin
[21:02:08] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[21:02:08] [main/INFO]: Disabling com.ishland.c2me.threading.worldgen.mixin
[21:02:08] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 2 override(s) found
[21:02:09] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[21:02:09] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton]) disables it and children
[21:02:09] [main/INFO]: === Clean Logs will filter from this point on. ===
[21:02:09] [main/INFO]: === Messages containing the following phrases will be filtered out: ===
[21:02:09] [main/INFO]: »
[21:02:09] [main/INFO]: spawn
[21:02:14] [main/INFO]: Building unoptimized datafixer
[21:02:16] [main/INFO]: Detected Java version 17. Enabling Java 16 features.
[21:02:16] [main/INFO]: [EssentialCommands]: Mod Load Initiated.
[21:02:17] [main/INFO]: [EssentialCommands]: Mod Load Complete.
[21:02:18] [ForkJoinPool.commonPool-worker-1/INFO]: Essential Commands is up to date!
[21:02:19] [main/INFO]: [Homabric:INFO] Classic commands enabled!
[21:02:19] [main/INFO]: [STDOUT]: Loading Image2Map...
[21:02:19] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[21:02:19] [main/INFO]: Several people are typing...
[21:02:20] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[21:02:20] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[21:02:20] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[21:02:20] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[21:02:20] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[21:02:20] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[21:02:20] [Via-Mappingloader-3/INFO]: Loading 1.16 -> 1.16.2 mappings...
[21:02:20] [Via-Mappingloader-2/INFO]: Loading 1.16.2 -> 1.17 mappings...
[21:02:20] [Via-Mappingloader-1/INFO]: Loading 1.17 -> 1.18 mappings...
[21:02:20] [Via-Mappingloader-0/INFO]: Loading 1.18 -> 1.19 mappings...
[21:02:20] [ViaFabric-0/WARN]: There is a newer plugin version available: 4.4.2, you're on: 4.4.0
[21:02:20] [ViaFabric-0/INFO]: ViaVersion detected server version: 1.19 (759)
[21:02:20] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dedicatedmcupnp'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:353) ~[com_fasterxml_jackson_dataformatyaml-2.13.0-64745faae2d50d23.jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.13.0-64745faae2d50d23.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[com_fasterxml_jackson_core_jacksbind-2.12.4-82a99bb0904951ea.jar:?]
	at pigcart.dedicatedmcupnp.DedicatedMcUpnp.onInitialize(DedicatedMcUpnp.java:67) ~[dedicatedmcupnp-1.2.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
	... 7 more
[21:02:21] [ViaFabric-0/INFO]: Finished mapping loading, shutting down loader executor!

This is the full log.
i already reinstalled it multiple times

**Comment by PigCart** [comment]
alright think I got it, seems like essential commands was loading a different version of the same thing. download the artifacts from here and see if dedicatedmcupnp-1.2.2.jar works for you. https://github.com/PigCart/UPeeNPiss/actions/runs/3201117379

**Comment by LazyGamer1111** [comment]
Thanks, it worked!
But something annoying, turns out upnp is disabled on my network (i didn't check because i am not allowed to change the settings of our router and i don't know the password).
But still thanks for the info!
